---
- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600
- name: Install dirmngr in order to be able to install the apt signing key
  apt:
    pkg:
      - dirmngr
      - apt-transport-https
- name: Add nodesource signing key on remote server to keyring
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    id: 6F71F525282841EEDAF851B42F59B5F99B1BE0B4
    keyring: /etc/apt/trusted.gpg.d/nodesource.gpg
    state: present
- name: Add apt repo for Nodejs
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/trusted.gpg.d/nodesource.gpg] https://deb.nodesource.com/node_{{ node_major_release }}.x nodistro main"
    state: present
- name: Install NodeJS
  apt:
    pkg: nodejs
- name: Install browser-sync
  npm:
    name: browser-sync
    global: yes
    version: "{{ browser_sync_version }}"
  environment:
    npm_config_prefix: "{{ npm_config_prefix }}"
  tags: browser-sync
